const HOST = 'https://www.jshhfl.com/xwdj/';
module.exports = {
  // 登录接口
  loginUrl: `${HOST}login.do`,
  // 获取帖子列表
  getPostingsUrl: `${HOST}findCommunityHomePage.do`,
  // 下拉加载更多
  getMorePostingUrl: `${HOST}findCommunityMore.do`,
  // 帖子点赞
  likesUrl: `${HOST}likeCommunity.do`,
  // 帖子搜索
  searchUrl: `${HOST}vagueSearch.do`,
  // 帖子详情
  postingsDetailUrl: `${HOST}findCommunityByCID.do`,
  // 查询帖子评论
  postingsCommentUrl: `${HOST}findComment.do`,
  // 查询帖子点赞
  postingsLikesUrl: `${HOST}findlikeUserByCID.do`,
  // 保存评论帖子内容
  savePostingsCommentUrl: `${HOST}releaseCommentToCommunity.do`,
  // 删除帖子
  deletePostingsUrl: `${HOST}deleteComunity.do`,
  // 上传图片
  upLoadPicUrl: `${HOST}publicPic.do`,
  // 发布帖子
  pushPostingsUrl: `${HOST}publicCommunity.do`,
  // 获取地图markes
  getMapMarkesUrl: `${HOST}findAllPosition.do`,
  // 地图marke点详情
  markeDetailUrl: `${HOST}findPositionDetail.do`,
  // 添加近期工作
  addWorkUrl: `${HOST}addWork.do`,
  // 个人积分信息
  findMyPointUrl: `${HOST}findMyPoint.do`,
  // 积分列表
  pointListUrl: `${HOST}findOrgOrder.do`,
  // 个人中心信息
  userInfoUrl: `${HOST}fingByOrgID.do`,
  // 修改个人头像
  changeAvatarUrl: `${HOST}modifyAvatar.do`,
  // 修改密码
  changePasswordUrl: `${HOST}modifyPassword.do`,
  // 查看我的近期工作
  getMyWorkUrl: `${HOST}findMyWork.do`,
  // 删除近期工作
  deleteWorkUrl: `${HOST}deleteWork.do`,
  // 获取已发帖子列表
  getAlreadyPostingsUrl: `${HOST}findMeetingByOrgID.do`,
  // 保存党组织信息
  saveUserInfoUrl: `${HOST}modifyOrg.do`,
  // 修改近期工作
  changeWorkUrl: `${HOST}modifyWork.do`,
  // 确认近期工作
  sureWorkUrl: `${HOST}modifyWorkStatus.do`,
  // 获取消息
  getMessagesUrl: `${HOST}findAllMessage.do`,
  // 确认是否同意删除党员
  sureMessageUrl: `${HOST}backMessage.do`,
  // 删除消息
  deleteMesageUrl: `${HOST}deleteMesage.do`
}